Repository GSM-MSG/GCMS-Android, pull requests merged in 2022-03, with the labels that each got.

#7 🔀 :: (#5) bottom navigation
  .idea/misc.xml
  app/src/main/java/com/msg/gcms/ui/component/free/FreeFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/main/MainActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/main/PageChangeCallback.kt
  app/src/main/java/com/msg/gcms/ui/component/main/PagerAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/major/MajorFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/personal/PersonalFragment.kt
  app/src/main/res/drawable/ic_free_text_activate.xml
  app/src/main/res/drawable/ic_free_text_close.xml
  app/src/main/res/drawable/ic_major_text_activate.xml
  app/src/main/res/drawable/ic_major_text_close.xml
  app/src/main/res/drawable/ic_personal_text_activate.xml
  app/src/main/res/drawable/ic_personal_text_close.xml
  app/src/main/res/drawable/selector_nav_bg.xml
  app/src/main/res/drawable/selector_nav_text_free.xml
  app/src/main/res/drawable/selector_nav_text_major.xml
  app/src/main/res/drawable/selector_nav_text_personal.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_free.xml
  app/src/main/res/layout/fragment_major.xml
  app/src/main/res/layout/fragment_personal.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#9 📝 :: login 화면 구현
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/ui/component/login/LoginActivity.kt
  app/src/main/res/drawable/ic_login_btn.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/font/notosans.ttf
  app/src/main/res/font/roboto.ttf
  app/src/main/res/layout/activity_login.xml
  buildSrc/build/classes/kotlin/main/Dependency$AndroidTest.class
  buildSrc/build/classes/kotlin/main/Dependency$AndroidX.class
  buildSrc/build/classes/kotlin/main/Dependency$BottomNav.class
  buildSrc/build/classes/kotlin/main/Dependency$Google.class
  buildSrc/build/classes/kotlin/main/Dependency$Libraries.class
  buildSrc/build/classes/kotlin/main/Dependency$UnitTest.class
  buildSrc/build/classes/kotlin/main/Versions.class
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/counters.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab_i
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
Labels: bug, enhancement

#12 🔀 :: (#10) 가입 대기자명단 페이지 XML 작성
  .idea/misc.xml
  app/src/main/java/com/msg/gcms/ui/component/application/ApplicationFragment.kt
  app/src/main/res/drawable/ic__announcement_btn.xml
  app/src/main/res/drawable/ic_back_btn.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_application.xml
  app/src/main/res/values/strings.xml
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab_i
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
Labels: enhancement

#14 🔀 :: (#8) app bar
  .idea/misc.xml
  app/src/main/java/com/msg/gcms/ui/base/BaseViewModel.kt
  app/src/main/java/com/msg/gcms/ui/component/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/free/FreeFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/main/MainActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/main/PagerAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/major/MajorFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/personal/PersonalFragment.kt
  app/src/main/java/com/msg/viewmodel/MainViewModel.kt
  app/src/main/res/drawable/ic_add_club.xml
  app/src/main/res/drawable/ic_alarm.xml
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/drawable/selector_nav_color.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_club.xml
  app/src/main/res/layout/fragment_free.xml
  app/src/main/res/layout/fragment_major.xml
  app/src/main/res/layout/fragment_personal.xml
Labels: enhancement

#17 ⚙ 클럽 생성 페이지 XML
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/MakeClubFragment.kt
  app/src/main/res/drawable/bg_banner_placeholder.xml
  app/src/main/res/drawable/bg_club_type.xml
  app/src/main/res/drawable/bg_make_club_et.xml
  app/src/main/res/drawable/ic_banner_placeholder.xml
  app/src/main/res/drawable/selector_club_type.xml
  app/src/main/res/drawable/selector_make_club_text.xml
  app/src/main/res/layout/fragment_make_club.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
Labels: enhancement

#18 🔀 :: (#16) profile UI
  app/src/main/java/com/msg/gcms/ui/component/main/MainActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileClubAdapter.kt
  app/src/main/res/drawable/bg_club_img.xml
  app/src/main/res/drawable/bg_club_txt.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_club.xml
  app/src/main/res/layout/item_my_club.xml
  app/src/main/res/navigation/club_fragment_graph.xml
Labels: enhancement

#24 🔀 :: (#19) club UI
  app/google-services.json
  app/src/main/java/com/msg/gcms/ui/component/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/club/home/HomeFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/main/MainActivity.kt
  app/src/main/res/drawable/bg_club_submit.xml
  app/src/main/res/drawable/bg_detail_club.xml
  app/src/main/res/layout/fragment_club.xml
  app/src/main/res/layout/fragment_club_detail.xml
  app/src/main/res/layout/fragment_club_home.xml
  app/src/main/res/navigation/club_fragment_graph.xml
Labels: FEATURE

#26 🔀 :: (#25) profile edit
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileActivity.kt
  app/src/main/res/layout/fragment_make_club.xml
Labels: FEATURE

#30 ⚙ :: 로그인 페이지를 변경합니다.
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/ui/component/login/LoginActivity.kt
  buildSrc/build/classes/kotlin/main/Dependency$Rx.class
  buildSrc/build/classes/kotlin/main/Versions.class
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/counters.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab_i
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/source-roots/buildSrc/source-roots.txt
Labels: CORRECTIONS

#31 Create LICENSE
  LICENSE
Labels: DOCS

#33 ⚙ :: 로그인 페이지 생성
  .idea/misc.xml
  app/src/main/res/drawable/bg_login_btn.xml
  app/src/main/res/drawable/bg_sign_btn.xml
  app/src/main/res/drawable/ic_login_btn.xml
  app/src/main/res/drawable/ic_msg_logo.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  buildSrc/build/libs/buildSrc.jar
Labels: CORRECTIONS

#35 ⚙ :: 코드 정리 및 로그인, 회원가입
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/ui/component/intro/IntroActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/login/LoginFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/registration/RegistrationFragment.kt
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_add_member.xml
  app/src/main/res/layout/fragment_club_detail.xml
  app/src/main/res/layout/fragment_club_home.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_make_club.xml
  app/src/main/res/layout/fragment_registration.xml
  app/src/main/res/layout/item_my_club.xml
  app/src/main/res/layout/list_club_member.xml
  app/src/main/res/layout/list_search_member.xml
Labels: FEATURE

#36 🔀 :: (#27) remove viewpager
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/java/com/msg/gcms/ui/base/BaseActivity.kt
  app/src/main/java/com/msg/gcms/ui/base/BaseFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/club/home/HomeFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/main/MainActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/main/PageChangeCallback.kt
  app/src/main/java/com/msg/gcms/ui/component/main/PagerAdapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_club.xml
  app/src/main/res/layout/fragment_club_home.xml
  app/src/main/res/navigation/bottom_nav_graph.xml
Labels: FEATURE

#38 ⚙ :: LoginActivity XML
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/ui/component/intro/IntroActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/login/LoginActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/login/LoginFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/registration/RegistrationActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/registration/RegistrationFragment.kt
  app/src/main/res/color/text_input_layout_stroke_color.xml
  app/src/main/res/drawable/bg_login_edit_text.xml
  app/src/main/res/drawable/ic_baseline_email_24.xml
  app/src/main/res/drawable/ic_baseline_lock_24.xml
  app/src/main/res/drawable/ic_group_17011.xml
  app/src/main/res/drawable/ic_gsm_hs_kr.xml
  app/src/main/res/drawable/ic_login_background.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_registration.xml
  app/src/main/res/layout/fragment_registration.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: FEATURE

#40 🔀 :: Data Binding 오류 해결
  app/src/main/java/com/msg/gcms/ui/component/club/home/HomeFragment.kt
  app/src/main/res/layout/fragment_club_home.xml
Labels: CORRECTIONS

#43 🔀 :: RegistrationActivity setting
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/java/com/msg/gcms/ui/component/login/LoginActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/registration/RegistrationActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_registration.xml
  app/src/main/res/values/strings.xml
Labels: FEATURE

#47 (#46)🔀 :: auth dataclass 생성
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Login.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Logout.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Refresh.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Register.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Verify.kt
Labels: FEATURE

#50 🔀 :: 이메일 인증화면 구현
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/ui/component/registration/EmailCheckFragment.kt
  app/src/main/res/drawable/ic_email_check_letter.xml
  app/src/main/res/drawable/ic_email_check_textinput.xml
  app/src/main/res/drawable/ic_send_again_btn.xml
  app/src/main/res/layout/fragment_email_check.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
Labels: FEATURE

#51 🔀 :: string, gradle 파일 수정
  app/build.gradle.kts
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: CORRECTIONS

#57 🔀 (56) :: edit data class code
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Login.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Logout.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Refresh.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Register.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Verify.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/request/LoginRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/request/LogoutRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/request/QueryString.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/request/RefreshRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/request/RegisterRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/response/LoginResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/response/RefreshResponse.kt
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
Labels: CORRECTIONS

#61 🔀 :: 이메일 인증 페이지 Refactor
  .idea/misc.xml
  app/src/main/java/com/msg/gcms/ui/component/emailcheck/EmailCheckFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/signUp/SignUpFragment.kt
  app/src/main/java/com/msg/viewmodel/RegistrationViewModel.kt
  app/src/main/res/navigation/registration_graph.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
Labels: FEATURE, HELP, REFAC

#67 🔀 :: 스플래시 화면 구현
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/ui/component/splash/SplashActivity.kt
  app/src/main/res/drawable/ic_splash_line.xml
  app/src/main/res/drawable/ic_splash_logo.xml
  app/src/main/res/drawable/ic_splash_text.xml
  app/src/main/res/layout/activity_splash.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
Labels: FEATURE
