Repository GSM-MSG/GCMS-Android, pull requests merged in 2022-05, with the labels that each got.

#95 🔀 :: (#41) login logic
  app/src/main/java/com/msg/gcms/data/remote/datasource/CommonDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/CommonDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/request/LoginRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/network/CommonAPI.kt
  app/src/main/java/com/msg/gcms/data/repository/CommonRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/di/module/UserCaseModule.kt
  app/src/main/java/com/msg/gcms/domain/repository/CommonRepository.kt
  app/src/main/java/com/msg/gcms/domain/usecase/common/LoginUseCase.kt
  app/src/main/java/com/msg/gcms/ui/component/login/LoginActivity.kt
  app/src/main/java/com/msg/viewmodel/LoginViewModel.kt
Labels: FEATURE

#99 🔀 (#98) :: EventWrapper 사용
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/ktlint.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/base/di/GCMSApplication.kt
  app/src/main/java/com/msg/gcms/base/di/module/.gitkeep
  app/src/main/java/com/msg/gcms/base/di/module/DataSourceModule.kt
  app/src/main/java/com/msg/gcms/base/di/module/NetworkModule.kt
  app/src/main/java/com/msg/gcms/base/di/module/RepositoryModule.kt
  app/src/main/java/com/msg/gcms/base/di/module/UserCaseModule.kt
  app/src/main/java/com/msg/gcms/base/utils/Event.kt
  app/src/main/java/com/msg/gcms/data/remote/network/CommonAPI.kt
  app/src/main/java/com/msg/gcms/data/remote/network/loginInterceptor.kt
  app/src/main/java/com/msg/gcms/domain/usecase/common/RegistrationUseCase.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/emailcheck/EmailCheckFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/main/MainActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/postemail/PostEmailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/signUp/SignUpFragment.kt
  app/src/main/java/com/msg/gcms/ui/dialog/EmailFailureDialogFragment.kt
  app/src/main/java/com/msg/viewmodel/MainViewModel.kt
  app/src/main/java/com/msg/viewmodel/MakeClubViewModel.kt
  app/src/main/java/com/msg/viewmodel/RegistrationViewModel.kt
Labels: BUG, CORRECTIONS

#101 🔀 (#100) :: ktlint 사용 및 이메일 체크 로직 수정
  app/build.gradle.kts
  app/src/androidTest/java/com/msg/gcms/ExampleInstrumentedTest.kt
  app/src/main/java/com/msg/gcms/base/di/GCMSApplication.kt
  app/src/main/java/com/msg/gcms/base/di/module/DataSourceModule.kt
  app/src/main/java/com/msg/gcms/base/di/module/NetworkModule.kt
  app/src/main/java/com/msg/gcms/base/di/module/RepositoryModule.kt
  app/src/main/java/com/msg/gcms/base/di/module/UserCaseModule.kt
  app/src/main/java/com/msg/gcms/base/utils/Event.kt
  app/src/main/java/com/msg/gcms/data/local/dao/LoginAccessToken.kt
  app/src/main/java/com/msg/gcms/data/local/dao/LoginRefreshToken.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/CommonDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/CommonDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/request/CodeIssuanceRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/request/LoginRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/request/LogoutRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/request/QueryString.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/request/RefreshRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/request/RegisterRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/response/LoginResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/response/RefreshResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/base/BaseResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/network/CommonAPI.kt
  app/src/main/java/com/msg/gcms/data/remote/network/loginInterceptor.kt
  app/src/main/java/com/msg/gcms/data/repository/CommonRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/domain/repository/CommonRepository.kt
  app/src/main/java/com/msg/gcms/domain/usecase/common/LoginUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/common/RegistrationUseCase.kt
  app/src/main/java/com/msg/gcms/ui/base/BaseActivity.kt
  app/src/main/java/com/msg/gcms/ui/base/BaseFragment.kt
  app/src/main/java/com/msg/gcms/ui/base/BaseViewModel.kt
  app/src/main/java/com/msg/gcms/ui/component/application/ApplicationFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/club/home/HomeFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/MakeClubActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubIntroduce/ClubIntroduceFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubType/ClubTypeFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/emailcheck/EmailCheckFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/intro/IntroActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/login/LoginActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/main/MainActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/member/AddMemberFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/postemail/PostEmailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileClubAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/registration/RegistrationActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/signUp/SignUpFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/splash/SplashActivity.kt
  app/src/main/java/com/msg/gcms/ui/dialog/EmailFailureDialogFragment.kt
  app/src/main/java/com/msg/viewmodel/LoginViewModel.kt
  app/src/main/java/com/msg/viewmodel/MainViewModel.kt
  app/src/main/java/com/msg/viewmodel/MakeClubViewModel.kt
  app/src/main/java/com/msg/viewmodel/RegistrationViewModel.kt
  app/src/test/java/com/msg/gcms/ExampleUnitTest.kt
  buildSrc/build/20220505_16038610776546875870.compiler.options
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  gradlew
Labels: CORRECTIONS

#103 🔀 :: (#102) 빌드 실패 수정
  app/build.gradle.kts
  app/src/main/java/com/msg/gcms/data/remote/dto/.gitkeep
  buildSrc/build/20220505_16038610776546875870.compiler.options
Labels: BUG, CORRECTIONS

#109 🔀 :: (#108)메니페스트 및 네비게이션 그래프 수정,삭제
  app/src/main/AndroidManifest.xml
  app/src/main/res/navigation/registration_graph.xml
  buildSrc/build/libs/buildSrc.jar
Labels: BUG, CORRECTIONS

#111 🔀 :: (#97) user profile UI
  .idea/misc.xml
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileActivity.kt
  app/src/main/res/drawable/ic_default_profile.xml
  app/src/main/res/drawable/ic_logout_btn.xml
  app/src/main/res/layout/activity_profile.xml
Labels: FEATURE

#115 🔀 :: (#114) intro animition
  app/src/main/java/com/msg/gcms/ui/component/intro/IntroActivity.kt
  app/src/main/res/anim/intro_animation.xml
  app/src/main/res/layout/activity_intro.xml
Labels: FEATURE

#118 🔀 :: (#117) Club part networking processing
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/base/di/module/DataSourceModule.kt
  app/src/main/java/com/msg/gcms/base/di/module/NetworkModule.kt
  app/src/main/java/com/msg/gcms/base/di/module/RepositoryModule.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/ClubDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/ClubDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/ImageDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/ImageDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/Image/ImageResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/request/CreateClubRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/request/ModifyClubInfoRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/network/ClubAPI.kt
  app/src/main/java/com/msg/gcms/data/remote/network/ImageAPI.kt
  app/src/main/java/com/msg/gcms/data/repository/ClubRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/data/repository/ImageRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/domain/repository/ClubRepository.kt
  app/src/main/java/com/msg/gcms/domain/repository/ImageRepository.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubIntroduce/ClubIntroduceFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubType/ClubTypeFragment.kt
  app/src/main/res/layout/fragment_club_introduce.xml
  app/src/main/res/layout/fragment_club_type.xml
  app/src/main/res/layout/fragment_make_club_detail.xml
  buildSrc/build/20220516_6223748997582931568.compiler.options
Labels: FEATURE, CORRECTIONS

#120 🔀 :: (#119) user api
  app/src/main/java/com/msg/gcms/base/di/module/DataSourceModule.kt
  app/src/main/java/com/msg/gcms/base/di/module/NetworkModule.kt
  app/src/main/java/com/msg/gcms/base/di/module/RepositoryModule.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/UserDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/UserDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/user/request/UserDeleteRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/user/request/UserProfileRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/user/request/UserSearchRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/network/UserAPI.kt
  app/src/main/java/com/msg/gcms/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/domain/repository/UserRepository.kt
Labels: FEATURE

#123 🔀 :: (#116) profile club
  app/src/main/java/com/msg/gcms/data/remote/datasource/UserDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/UserDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/user/response/ClubData.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/user/response/UserData.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/user/response/UserInfoResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/network/UserAPI.kt
  app/src/main/java/com/msg/gcms/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/domain/repository/UserRepository.kt
  app/src/main/java/com/msg/gcms/domain/usecase/user/ProfileUseCase.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileClubAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileClubFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileNoClubFragment.kt
  app/src/main/java/com/msg/viewmodel/ProfileViewModel.kt
  app/src/main/res/drawable/bg_find_club_btn.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_profile_club.xml
  app/src/main/res/layout/fragment_profile_no_club.xml
  app/src/main/res/values/colors.xml
Labels: FEATURE

#126 🔀 :: (#125) add gallery access permission check logic
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/msg/gcms/base/di/module/RepositoryModule.kt
  app/src/main/java/com/msg/gcms/data/local/entity/BannerImage.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/ClubInfoResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/ClubResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/MemberInfo.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/SummaryClubResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/UserInfo.kt
  app/src/main/java/com/msg/gcms/data/remote/network/ImageAPI.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/MakeClubActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/BannerAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubIntroduce/ClubIntroduceFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileActivity.kt
  app/src/main/res/layout/fragment_club_introduce.xml
  app/src/main/res/layout/fragment_make_club_detail.xml
  app/src/main/res/layout/list_club_picture.xml
  app/src/main/res/values/strings.xml
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/counters.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab_i
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/src/main/java/Versions.kt
Labels: FEATURE, CORRECTIONS

#129 🔀 :: (#124) main club
  app/src/main/java/com/msg/gcms/domain/usecase/club/ClubUseCase.kt
  app/src/main/java/com/msg/gcms/ui/component/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/club/home/HomeFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/main/MainActivity.kt
  app/src/main/java/com/msg/viewmodel/MainViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_club.xml
  app/src/main/res/layout/fragment_club_home.xml
  app/src/main/res/navigation/club_fragment_graph.xml
Labels: FEATURE

#133 🔀 :: (#110) oauth logic
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/.gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/data/remote/datasource/CommonDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/CommonDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/request/RegisterRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/response/RegisterResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/network/CommonAPI.kt
  app/src/main/java/com/msg/gcms/data/repository/CommonRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/domain/repository/CommonRepository.kt
  app/src/main/java/com/msg/gcms/domain/usecase/common/RegistrationUseCase.kt
  app/src/main/java/com/msg/gcms/ui/component/intro/IntroActivity.kt
  app/src/main/java/com/msg/viewmodel/RegistrationViewModel.kt
  app/src/main/res/values/.gitignore
  app/src/main/res/values/strings.xml
  build.gradle.kts
  buildSrc/build/classes/kotlin/main/Dependency$Google.class
  buildSrc/build/classes/kotlin/main/Versions.class
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/counters.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab_i
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  gradlew
Labels: FEATURE

#139 🔐 :: google-services.json 파일 암호화
  .github/workflows/android.yml
  app/google-services.json.gpg
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
  buildSrc/build/source-roots/buildSrc/source-roots.txt
Labels: DOCS, FEATURE

#141 🔀 :: (#135) acitivity image setting
  .idea/misc.xml
  app/src/main/java/com/msg/gcms/data/local/entity/ActivityPhotoType.kt
  app/src/main/java/com/msg/gcms/ui/adapter/ActivityPhotosAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/ActivityPhotosAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/utils/ItemDecorator.kt
  app/src/main/res/drawable/bg_club_image_rv.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/layout/fragment_make_club_detail.xml
  app/src/main/res/layout/list_club_picture.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
Labels: FEATURE

#143 🔀 :: (#140) mypage v2.0
  app/src/main/java/com/msg/gcms/data/remote/datasource/CommonDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/CommonDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/user/response/AftersData.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/user/response/UserInfoResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/network/CommonAPI.kt
  app/src/main/java/com/msg/gcms/data/repository/CommonRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/domain/repository/CommonRepository.kt
  app/src/main/java/com/msg/gcms/ui/component/intro/IntroActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileAfterSchoolFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileClubFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileNoAfterSchoolFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileNoClubFragment.kt
  app/src/main/java/com/msg/viewmodel/ProfileViewModel.kt
  app/src/main/res/drawable/bg_club_img.xml
  app/src/main/res/drawable/bg_profile_list.xml
  app/src/main/res/drawable/bg_profile_nothing_list.xml
  app/src/main/res/drawable/ic_no_club.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_profile_after_school.xml
  app/src/main/res/layout/fragment_profile_club.xml
  app/src/main/res/layout/fragment_profile_no_after_school.xml
  app/src/main/res/layout/fragment_profile_no_club.xml
  app/src/main/res/values/colors.xml
Labels: FEATURE

#146 🔀 :: (#128) afterschool UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/ui/component/afterschool/JoinAfterSchoolActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/main/MainActivity.kt
  app/src/main/res/drawable/ic_after_school_btn.xml
  app/src/main/res/drawable/ic_group_17655.xml
  app/src/main/res/drawable/ic_illust.xml
  app/src/main/res/drawable/ic_rectangle_941.xml
  app/src/main/res/drawable/ic_rectangle_946.xml
  app/src/main/res/layout/activity_join_after_school.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/afterschool_modal.xml
Labels: FEATURE
