Repository GSM-MSG/GCMS-Android, pull requests merged in 2022-06, with the labels that each got.

#152 pr template
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .idea/misc.xml
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/MemberInfo.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/MemberSummaryResponse.kt
  app/src/main/java/com/msg/gcms/ui/adapter/ActivityPhotosAdapter.kt
  app/src/main/java/com/msg/gcms/ui/adapter/ClubMemberAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
  app/src/main/res/layout/fragment_make_club_detail.xml
  app/src/main/res/layout/list_club_member.xml
Labels: DOCS

#150 🔀 :: (#142)Club Member RecyclerView 구현
  .idea/misc.xml
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/MemberInfo.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/MemberSummaryResponse.kt
  app/src/main/java/com/msg/gcms/ui/adapter/ActivityPhotosAdapter.kt
  app/src/main/java/com/msg/gcms/ui/adapter/ClubMemberAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
  app/src/main/res/layout/fragment_make_club_detail.xml
  app/src/main/res/layout/list_club_member.xml
Labels: FEATURE, REFAC

#153 🔀 :: (#147) token
  app/src/main/java/com/msg/gcms/base/di/GCMSApplication.kt
  app/src/main/java/com/msg/gcms/data/local/dao/LoginAccessToken.kt
  app/src/main/java/com/msg/gcms/data/local/dao/LoginRefreshToken.kt
  app/src/main/java/com/msg/gcms/data/local/dao/LoginToken.kt
  app/src/main/java/com/msg/gcms/data/remote/network/LoginInterceptor.kt
  app/src/main/java/com/msg/viewmodel/LoginViewModel.kt
  app/src/main/java/com/msg/viewmodel/RegistrationViewModel.kt
Labels: FEATURE

#170 🔀 :: 충돌로 인한 에러 해결
  app/src/main/java/com/msg/gcms/base/di/module/UserCaseModule.kt
  app/src/main/java/com/msg/gcms/ui/adapter/ClubMemberAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/viewmodel/ClubDetailViewModel.kt
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/counters.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab_i
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
Labels: BUG, CORRECTIONS

#173 🔀 :: develop 브랜치 에러 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/ui/adapter/ClubActivitysAdapter.kt
  app/src/main/java/com/msg/gcms/ui/adapter/DetailMemberAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/searchstudent/UserSearchActivity.kt
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
Labels: CORRECTIONS

#175 🔀 :: 디테일 페이지 onBackPressed 처리
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/main/MainActivity.kt
Labels: FEATURE

#178 🔀 :: (#158) profile club
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/user/response/UserInfoResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/network/UserAPI.kt
  app/src/main/java/com/msg/gcms/domain/usecase/common/LogoutUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/common/RefreshUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/common/RegistrationUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/user/EditProfileUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/user/ProfileUseCase.kt
  app/src/main/java/com/msg/gcms/ui/adapter/AfterSchoolListAdapter.kt
  app/src/main/java/com/msg/gcms/ui/adapter/EditorialClubList.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileAfterSchoolFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileClubFragment.kt
  app/src/main/java/com/msg/viewmodel/MainViewModel.kt
  app/src/main/java/com/msg/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/msg/viewmodel/RegistrationViewModel.kt
  app/src/main/res/drawable/bg_after_school.xml
  app/src/main/res/drawable/bg_profile_img.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_profile_after_school.xml
  app/src/main/res/layout/fragment_profile_club.xml
  app/src/main/res/layout/list_after_school.xml
  app/src/main/res/layout/list_club_editorial.xml
Labels: FEATURE

#180 ⚡️ :: (#164) 동아리 생성 기능 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/msg/gcms/data/remote/datasource/ImageDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/ImageDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/Image/ImageResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/request/CreateClubRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/request/EmailType.kt
  app/src/main/java/com/msg/gcms/data/remote/network/ImageAPI.kt
  app/src/main/java/com/msg/gcms/data/repository/ImageRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/domain/repository/ImageRepository.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubIntroduce/ClubIntroduceFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/searchstudent/StudentSearchFragment.kt
  app/src/main/java/com/msg/viewmodel/MainViewModel.kt
  app/src/main/java/com/msg/viewmodel/MakeClubViewModel.kt
  app/src/main/res/layout/fragment_make_club_detail.xml
Labels: FEATURE

#182 🔀 :: (#179) logout
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/data/remote/datasource/UserDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/UserDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/network/UserAPI.kt
  app/src/main/java/com/msg/gcms/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/domain/repository/UserRepository.kt
  app/src/main/java/com/msg/gcms/domain/usecase/user/DeleteUserUseCase.kt
  app/src/main/java/com/msg/gcms/ui/adapter/AfterSchoolListAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/intro/IntroActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/withdrawal/WithdrawalActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/withdrawal/WithdrawalDialog.kt
  app/src/main/java/com/msg/viewmodel/WithdrawalViewModel.kt
  app/src/main/res/drawable/bg_withdrawal_active_btn.xml
  app/src/main/res/drawable/bg_withdrawal_gradient.xml
  app/src/main/res/drawable/bg_withdrawal_sleep_btn.xml
  app/src/main/res/drawable/bg_withdrawal_warning.xml
  app/src/main/res/drawable/ic_check_btn.xml
  app/src/main/res/drawable/ic_checked_btn.xml
  app/src/main/res/drawable/ic_logout_option.xml
  app/src/main/res/drawable/ic_withdrawal_btn.xml
  app/src/main/res/drawable/ic_withdrawal_gcms.xml
  app/src/main/res/drawable/ic_withdrawal_point.xml
  app/src/main/res/drawable/selector_withdrawal_btn.xml
  app/src/main/res/drawable/selector_withdrawal_check_btn.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_withdrawal.xml
  app/src/main/res/layout/fragment_profile_club.xml
  app/src/main/res/layout/fragment_profile_no_after_school.xml
  app/src/main/res/layout/logout_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
Labels: FEATURE

#185 🔀 :: (#184) 서비스 이용 약관, 개인정보 처리 방침 연결
  .idea/misc.xml
  app/.gitignore
  app/src/main/java/com/msg/gcms/base/di/module/BASE_URL.kt
  app/src/main/java/com/msg/gcms/base/di/module/NetworkModule.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/ClubInfoResponse.kt
  app/src/main/java/com/msg/gcms/ui/adapter/ActivityPhotosAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/intro/IntroActivity.kt
  app/src/main/res/drawable/ic_club_delete.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_gsm_hs_kr.xml
  app/src/main/res/drawable/ic_login_background.xml
  app/src/main/res/drawable/ic_person_two.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
  buildSrc/build/source-roots/buildSrc/source-roots.txt
Labels: FEATURE
