Repository GSM-MSG/GCMS-Android, pull requests merged in 2022-07, with the labels that each got.

#191 🔀 :: (#181) create progress bar
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/searchstudent/StudentSearchFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileAfterSchoolFragment.kt
  app/src/main/res/layout/progress_bar.xml
  app/src/main/res/raw/whale_lottie.json
  buildSrc/build/classes/kotlin/main/Dependency$Lottie.class
  buildSrc/build/classes/kotlin/main/Dependency.class
  buildSrc/build/classes/kotlin/main/Versions.class
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab_i
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
Labels: FEATURE

#193 Hotfix/192 banner img error
  .idea/misc.xml
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/viewmodel/MakeClubViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
Labels: BUG

#195 🔀 :: (#194)로그 삭제
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
Labels: CORRECTIONS

#198 🔀 :: (#197) delete file
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/ui/component/afterschool/JoinAfterSchoolActivity.kt
  app/src/main/res/anim/edit_text_error_animation.xml
  app/src/main/res/anim/edit_text_error_interrupt.xml
  app/src/main/res/anim/intro_animation.xml
  app/src/main/res/anim/login_animation1.xml
  app/src/main/res/anim/login_animation2.xml
  app/src/main/res/color/text_input_layout_stroke_color.xml
  app/src/main/res/drawable/bg_club_promotion.xml
  app/src/main/res/drawable/bg_club_submit.xml
  app/src/main/res/drawable/bg_edit_text_.xml
  app/src/main/res/drawable/bg_login_btn.xml
  app/src/main/res/drawable/bg_login_edit_text.xml
  app/src/main/res/drawable/bg_login_edit_text_error.xml
  app/src/main/res/drawable/bg_serach_edit_text.xml
  app/src/main/res/drawable/bg_summary_club_img.xml
  app/src/main/res/drawable/bg_wave1.xml
  app/src/main/res/drawable/bg_wave2.xml
  app/src/main/res/drawable/ic_after_school_btn.xml
  app/src/main/res/drawable/ic_baseline_email_24.xml
  app/src/main/res/drawable/ic_baseline_lock_24.xml
  app/src/main/res/drawable/ic_club_delete.xml
  app/src/main/res/drawable/ic_club_member_btn.xml
  app/src/main/res/drawable/ic_current_page.xml
  app/src/main/res/drawable/ic_default_profile.xml
  app/src/main/res/drawable/ic_dialog_bg.xml
  app/src/main/res/drawable/ic_dialog_btn_bg.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_email_check_failure_edittext.xml
  app/src/main/res/drawable/ic_email_check_letter.xml
  app/src/main/res/drawable/ic_erase_btn.xml
  app/src/main/res/drawable/ic_eye.xml
  app/src/main/res/drawable/ic_eye_close.xml
  app/src/main/res/drawable/ic_eye_open.xml
  app/src/main/res/drawable/ic_group_17011.xml
  app/src/main/res/drawable/ic_main_background.xml
  app/src/main/res/drawable/ic_person_two.xml
  app/src/main/res/drawable/ic_send_again_btn.xml
  app/src/main/res/drawable/selector_check_box.xml
  app/src/main/res/drawable/selector_club_type.xml
  app/src/main/res/drawable/selector_email_check.xml
  app/src/main/res/drawable/selector_make_club_text.xml
  app/src/main/res/drawable/selector_user_check_list.xml
  app/src/main/res/layout/activity_join_after_school.xml
  app/src/main/res/layout/afterschool_modal.xml
Labels: REFAC

#199 🔀 :: (#196) 부자연스러운 로티 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/ui/base/LottieFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/viewmodel/ClubViewModel.kt
  app/src/main/res/layout/progress_bar.xml
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
Labels: CORRECTIONS

#201 🔀 :: (#165) 동아리 세부 페이지 사이드바 생성
  .idea/misc.xml
  app/src/main/java/com/msg/gcms/data/local/dao/LoginToken.kt
  app/src/main/java/com/msg/gcms/data/local/entity/DetailPageSideBar.kt
  app/src/main/java/com/msg/gcms/ui/adapter/AfterSchoolListAdapter.kt
  app/src/main/java/com/msg/gcms/ui/adapter/DetailSideBarAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/viewmodel/MakeClubViewModel.kt
  app/src/main/res/drawable/ic_club_delete.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_person_two.xml
  app/src/main/res/layout/detail_toolbar.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/header_layout.xml
  app/src/main/res/layout/list_detail_sidebar.xml
  app/src/main/res/menu/head_detail_menu.xml
  app/src/main/res/menu/member_detail_menu.xml
  app/src/main/res/values-w820dp/dimens.xml
  app/src/main/res/values/dimens.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
  buildSrc/build/source-roots/buildSrc/source-roots.txt
Labels: FEATURE

#202 🔀 :: (#200) 프로필 방과후 조회 제거
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileClubFragment.kt
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_profile_club.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
Labels: CORRECTIONS

#206 🔀 :: (#205)notionlink 앞에 https://
  app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubIntroduce/ClubIntroduceFragment.kt
Labels: FEATURE

#208 🔀 :: (#183) club member manage
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/base/di/module/NetworkModule.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/ClubDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/ClubDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/MemberInfo.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/MemberSummaryResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/network/ClubAPI.kt
  app/src/main/java/com/msg/gcms/data/repository/ClubRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/domain/repository/ClubRepository.kt
  app/src/main/java/com/msg/gcms/domain/usecase/club/ApplicantAcceptUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/club/ApplicantRejectUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/club/GetApplicantUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/club/GetMemberUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/club/MandateUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/club/UserKickUseCase.kt
  app/src/main/java/com/msg/gcms/ui/adapter/AfterSchoolListAdapter.kt
  app/src/main/java/com/msg/gcms/ui/adapter/ApplicantAdapter.kt
  app/src/main/java/com/msg/gcms/ui/adapter/EditorialClubAdapter.kt
  app/src/main/java/com/msg/gcms/ui/adapter/MemberAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/application/ApplicationFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/member_manage/MemberManageActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileClubFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/withdrawal/WithdrawalDialog.kt
  app/src/main/java/com/msg/viewmodel/MemberManageViewModel.kt
  app/src/main/res/drawable/bg_approve_btn.xml
  app/src/main/res/drawable/bg_dialog_cancel.xml
  app/src/main/res/drawable/bg_dialog_ok.xml
  app/src/main/res/drawable/bg_member_black_btn.xml
  app/src/main/res/drawable/bg_withdrawal_btn.xml
  app/src/main/res/drawable/ic__announcement_btn.xml
  app/src/main/res/layout/activity_member_management.xml
  app/src/main/res/layout/detail_dialog.xml
  app/src/main/res/layout/fragment_application.xml
  app/src/main/res/layout/list_applicant.xml
  app/src/main/res/layout/list_member.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: FEATURE

#212 🔀 :: (#210) delete club
  app/src/main/java/com/msg/gcms/data/remote/datasource/ClubDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/ClubDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/user/request/UserDeleteRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/network/ClubAPI.kt
  app/src/main/java/com/msg/gcms/data/remote/network/UserAPI.kt
  app/src/main/java/com/msg/gcms/data/repository/ClubRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/domain/repository/ClubRepository.kt
  app/src/main/java/com/msg/gcms/domain/usecase/club/ClubDeleteUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/user/ExitUseCase.kt
  app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileActivity.kt
  app/src/main/java/com/msg/viewmodel/ClubViewModel.kt
Labels: FEATURE

#213 🔀 :: (#209) profile bottom sheet
  app/src/main/java/com/msg/gcms/ui/component/withdrawal/WithdrawalDialog.kt
  app/src/main/res/values/themes.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
Labels: FEATURE

#214 🔀 :: (#189) edit club info
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/editclub/EditClubActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileActivity.kt
  app/src/main/java/com/msg/viewmodel/ClubDetailViewModel.kt
  app/src/main/java/com/msg/viewmodel/EditClubViewModel.kt
  app/src/main/res/layout/activity_edit_club.xml
  app/src/main/res/layout/fragment_detail.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
Labels: FEATURE

#215 🔀 :: (#211) 프로필에서 디테일로 넘어가기
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/ClubInfoResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/ClubResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/UserInfo.kt
  app/src/main/java/com/msg/gcms/ui/adapter/EditorialClubAdapter.kt
  app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/ui/component/main/MainActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/ui/component/profile/ProfileClubFragment.kt
  app/src/main/java/com/msg/viewmodel/ClubDetailViewModel.kt
  app/src/main/java/com/msg/viewmodel/ProfileViewModel.kt
  app/src/main/res/values/strings.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
  buildSrc/build/source-roots/buildSrc/source-roots.txt
Labels: FEATURE, CORRECTIONS
