Repository GSM-MSG/GCMS-Android, pull requests merged in 2023-03, with the labels that each got.

#331 🔀 :: (#330) - modify create club message
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/make_result/MakeClubResultFragment.kt
  app/src/main/res/drawable/bg_check_btn.xml
  app/src/main/res/drawable/ic_close_button.xml
  app/src/main/res/drawable/ic_email.xml
  app/src/main/res/drawable/ic_error.xml
  app/src/main/res/drawable/ic_server_error.xml
  app/src/main/res/drawable/ic_unknown.xml
  app/src/main/res/layout/fragment_make_club_result.xml
  app/src/main/res/navigation/club_maker_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: FEATURE

#332 🔀 :: (#330) - modify create club message
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/make_result/MakeClubResultFragment.kt
  app/src/main/res/layout/fragment_make_club_result.xml
Labels: BUG, FEATURE

#335 🔀 :: (#334) 동아리 생성 관련 이슈 해결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
Labels: FEATURE

#338 🔀 ::(#325) 무한 백 버튼 및 버그 해결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/search_student/StudentSearchFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditSearchFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/main/MainActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
  app/src/main/res/layout/activity_member_management.xml
Labels: BUG

#349 🔀 :: 동아리 거절 시 else case 수정
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
Labels: CORRECTIONS

#350 🔀 :: (#346) 디테일 페이지에서 클럽아이디 사라지는 버그 해결
  app/src/main/java/com/msg/gcms/data/remote/dto/club/get_club_detail/ClubMemberResponse.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/main/MainActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubDetailViewModel.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/MemberManageViewModel.kt
Labels: BUG

#357 🔀 :: (#354) 클럽 페이지 변경
  app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
Labels: CORRECTIONS

#360 Feature/354 profile
  app/src/main/java/com/msg/gcms/presentation/adapter/editorial_club/ClubType.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/editorial_club/EditorialClubAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileNoClubFragment.kt
  app/src/main/res/layout/list_club_editorial.xml
Labels: FEATURE

#356 🔀 :: (#354) - member
  app/src/main/java/com/msg/gcms/presentation/view/member/AddMemberFragment.kt
  app/src/main/res/layout/fragment_add_member.xml
Labels: CORRECTIONS

#355 🔀 :: (#354) - edit club
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditSearchFragment.kt
Labels: CORRECTIONS

#361 🔀 :: (#354) - modify that fragment base cycle
  app/src/main/java/com/msg/gcms/presentation/adapter/editorial_club/ClubType.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/editorial_club/EditorialClubAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/base/BaseFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_introduce/ClubIntroduceFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_type/ClubTypeFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/make_result/MakeClubResultFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/search_student/StudentSearchFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditSearchFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/member/AddMemberFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileNoClubFragment.kt
  app/src/main/res/layout/fragment_add_member.xml
  app/src/main/res/layout/list_club_editorial.xml
Labels: CORRECTIONS

#369 🔀 :: (#367) 가입 대기자 명단 불러오는 에러 해결
  app/src/main/java/com/msg/gcms/presentation/view/intro/IntroActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/progress/ProgressDialog.kt
Labels: BUG

#370 🔀 :: (#368) - 다이얼로그 중복 생성 이슈 해결
  app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
Labels: CORRECTIONS

#371 🔀 :: (#367) 반영 안 된 커밋
  app/src/main/res/layout/fragment_club_introduce.xml
  app/src/main/res/layout/fragment_edit_club.xml
Labels: CORRECTIONS

#372 🔀 :: (#368) - 동아리 활동사진 가로가 비율로 안되어있던거 해결
  app/build.gradle.kts
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/list_detail_club_promotion.xml
Labels: CORRECTIONS

#374 🔀 :: (#373) - 클럽 리스트 받는 로직 이그노어 path추가
  app/src/main/java/com/msg/gcms/data/remote/network/LoginInterceptor.kt
Labels: CORRECTIONS

#375 🔀 - (#365) :: The menu bar is available for clubs that you are not included in.
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/res/layout/fragment_detail.xml
Labels: CORRECTIONS

#381 🔀 :: (#379) - GAuth v1.0.7 적용
  app/src/main/java/com/msg/gcms/presentation/view/intro/IntroActivity.kt
  buildSrc/src/main/java/Versions.kt
Labels: CORRECTIONS

#380 🔀 :: (#378) FCM 세팅
  .github/workflows/android.yml
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/data/local/datasource/LocalDataSource.kt
  app/src/main/java/com/msg/gcms/data/local/datasource/LocalDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/local/datastorage/AuthDataStorage.kt
  app/src/main/java/com/msg/gcms/data/local/datastorage/AuthDataStorageImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/auth/request/RefreshRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/auth/request/SignInRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/network/LoginInterceptor.kt
  app/src/main/java/com/msg/gcms/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/domain/data/auth/SignInRequestData.kt
  app/src/main/java/com/msg/gcms/domain/repository/AuthRepository.kt
  app/src/main/java/com/msg/gcms/domain/usecase/auth/SaveTokenInfoUseCase.kt
  app/src/main/java/com/msg/gcms/presentation/service/GCMSMessagingService.kt
  app/src/main/java/com/msg/gcms/presentation/utils/ChangeScreenEvent.kt
  app/src/main/java/com/msg/gcms/presentation/view/intro/IntroActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/splash/SplashActivity.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/AuthViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
  build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
Labels: FEATURE

#383 🔀 :: (#376) - modify profile image to user profile image
  app/src/main/java/com/msg/gcms/data/mapper/UserMapper.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/user/UserDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/user/UserDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/user/get_profile_image/GetProfileImageResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/network/api/UserAPI.kt
  app/src/main/java/com/msg/gcms/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/domain/data/user/get_profile_image/GetProfileImageData.kt
  app/src/main/java/com/msg/gcms/domain/repository/UserRepository.kt
  app/src/main/java/com/msg/gcms/domain/usecase/user/GetProfileImageUseCase.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/main/MainActivity.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/MainViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_club.xml
Labels: FEATURE

#388 🔀 :: (#386) 스켈레톤 종료되지 않는 오류 해결
  app/src/main/java/com/msg/gcms/presentation/utils/ShimmerEvent.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/main/MainActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/MainViewModel.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ProfileViewModel.kt
Labels: BUG

#387 🔀 :: (#384) - 버튼 패딩 적용
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout/activity_member_management.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_withdrawal.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/xml/activity_profile_xml_constraintlayout_scene.xml
Labels: CORRECTIONS

#394 🔀 :: (#393) - ignore path수정
  app/src/main/java/com/msg/gcms/data/remote/network/LoginInterceptor.kt
Labels: CORRECTIONS

#398 🔀 :: (#397) - 디바이스 크기에 맞게 버튼크기 맞춰지도록 코드 변경
  app/src/main/java/com/msg/gcms/presentation/view/intro/IntroActivity.kt
  app/src/main/res/layout/activity_intro.xml
Labels: CORRECTIONS

#396 🔀 :: (#395) CD 세팅
  .github/workflows/android-cd.yml
  .github/workflows/android-ci.yml
Labels: FEATURE

#403 🔀 :: cd 변경
  .github/workflows/android-cd.yml
Labels: DOCS

#404 🔀 :: (#395) service_account 파일 따로 삽입
  .github/workflows/android-cd.yml
Labels: DOCS

#405 🔀 :: service_account 파일 생성 방식 변경
  .github/workflows/android-cd.yml
Labels: DOCS

#413 🔀 :: (#412) - 프로그래스 애니메이션 로티 이미지로 변경
  app/src/main/java/com/msg/gcms/presentation/base/LottieFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/intro/IntroActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/progress/ProgressDialog.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubViewModel.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/EditViewModel.kt
  app/src/main/res/layout/intro_progress_lottie.xml
  app/src/main/res/layout/progress_dialog.xml
  app/src/main/res/raw/progress_lottie.json
Labels: FEATURE, CORRECTIONS

#415 🔀 :: (#414) - splash에서 인터넷 연결을 검사하도록 로직 추가
  app/src/main/java/com/msg/gcms/presentation/view/splash/SplashActivity.kt
Labels: FEATURE
