Repository GSM-MSG/GCMS-Android, pull requests merged in 2023-02, with the labels that each got.

#236 🔀 :: (#234) - setting splash page
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/bg_splash.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
Labels: FEATURE

#237 🔀 :: (#235) 로그인 방식을 GAuth로 변경하고 토큰을 로컬에 저장
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/data/local/dao/TokenHandler.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/ClubDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/ClubDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/ImageDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/ImageDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/UserDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/UserDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/auth/request/SignInRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/auth/response/SignInResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/network/AuthAPI.kt
  app/src/main/java/com/msg/gcms/data/remote/network/LoginInterceptor.kt
  app/src/main/java/com/msg/gcms/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/data/repository/CommonRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/di/GCMSApplication.kt
  app/src/main/java/com/msg/gcms/di/module/DataSourceModule.kt
  app/src/main/java/com/msg/gcms/di/module/NetworkModule.kt
  app/src/main/java/com/msg/gcms/di/module/RepositoryModule.kt
  app/src/main/java/com/msg/gcms/di/module/UseCaseModule.kt
  app/src/main/java/com/msg/gcms/domain/datasource/CommonDataSource.kt
  app/src/main/java/com/msg/gcms/domain/repository/AuthRepository.kt
  app/src/main/java/com/msg/gcms/domain/repository/CommonRepository.kt
  app/src/main/java/com/msg/gcms/domain/usecase/auth/LogoutUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/auth/RefreshUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/auth/SignInUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/common/RegistrationUseCase.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/intro/IntroActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/splash/SplashActivity.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/AuthViewModel.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/RegistrationViewModel.kt
  app/src/main/java/com/msg/gcms/ui/component/intro/component/ProgressDialog.kt
  app/src/main/res/layout/activity_intro.xml
Labels: FEATURE, CORRECTIONS

#239 🔀 :: (#228) 화면 전환 애니메이션 적용
  app/src/main/java/com/msg/gcms/presentation/utils/ChangeScreenEvent.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/clubType/ClubTypeFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/intro/IntroActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileActivity.kt
  app/src/main/res/anim/enter_anim.xml
  app/src/main/res/anim/exit_anim.xml
  app/src/main/res/anim/no_anim.xml
  buildSrc/src/main/java/Versions.kt
Labels: FEATURE

#243 🔀 :: (#242) 프로필 페이지에서 방과후 부분 삭제
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileAfterSchoolFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileNoAfterSchoolFragment.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ProfileViewModel.kt
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_profile_after_school.xml
  app/src/main/res/layout/fragment_profile_club.xml
  app/src/main/res/layout/fragment_profile_no_after_school.xml
  app/src/main/res/xml/activity_profile_xml_constraintlayout_scene.xml
Labels: REFAC, CORRECTIONS

#246 🔀 :: (#238)자동로그인, 리프레쉬, 자체적인 로그아웃 추가
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/data/local/dao/TokenHandler.kt
  app/src/main/java/com/msg/gcms/data/local/database/.gitkeep
  app/src/main/java/com/msg/gcms/data/local/datasource/LocalDataSource.kt
  app/src/main/java/com/msg/gcms/data/local/datasource/LocalDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/local/datastorage/AuthDataStorage.kt
  app/src/main/java/com/msg/gcms/data/local/datastorage/AuthDataStorageImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/network/AuthAPI.kt
  app/src/main/java/com/msg/gcms/data/remote/network/LoginInterceptor.kt
  app/src/main/java/com/msg/gcms/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/di/GCMSApplication.kt
  app/src/main/java/com/msg/gcms/di/module/LocalDataStorageModule.kt
  app/src/main/java/com/msg/gcms/di/module/NetworkModule.kt
  app/src/main/java/com/msg/gcms/di/module/RepositoryModule.kt
  app/src/main/java/com/msg/gcms/di/module/UseCaseModule.kt
  app/src/main/java/com/msg/gcms/domain/repository/AuthRepository.kt
  app/src/main/java/com/msg/gcms/domain/usecase/auth/CheckLoginStatusUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/auth/LogoutUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/auth/SaveTokenInfoUseCase.kt
  app/src/main/java/com/msg/gcms/domain/usecase/auth/SignInUseCase.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/intro/IntroActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/splash/SplashActivity.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/AuthViewModel.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/SplashViewModel.kt
  app/src/main/java/com/msg/gcms/util/Extension.kt
Labels: FEATURE, CORRECTIONS

#244 🔀 :: 여러 번 요청 보내지는거 제어
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/MakeClubViewModel.kt
Labels: CORRECTIONS

#248 🔀 :: (#247)로그아웃 로직 작성
  app/src/main/java/com/msg/gcms/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/msg/gcms/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/msg/gcms/data/remote/network/AuthAPI.kt
  app/src/main/java/com/msg/gcms/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/di/module/UseCaseModule.kt
  app/src/main/java/com/msg/gcms/domain/repository/AuthRepository.kt
  app/src/main/java/com/msg/gcms/domain/usecase/auth/LogoutUseCase.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/AuthViewModel.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ProfileViewModel.kt
Labels: FEATURE, CORRECTIONS

#252 🔀 :: endpoint 수정
  app/src/main/java/com/msg/gcms/data/remote/network/api/ClubAPI.kt
  app/src/main/java/com/msg/gcms/data/remote/network/api/UserAPI.kt
Labels: BUG, CORRECTIONS

#260 🔀 :: (#259) CI에 캐시 추가
  .github/workflows/android.yml
Labels: CORRECTIONS

#257 🔀 :: (#255) - modify create club logic
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/gcms/data/local/entity/AddMemberType.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/club/get_club_detail/ClubMemberResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/club_member/get_club_member/MemberResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/club_member/member_expelled/MemberExpelledRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/user/search_user/GetSearchUserResponse.kt
  app/src/main/java/com/msg/gcms/domain/data/club/get_club_detail/ClubMemberData.kt
  app/src/main/java/com/msg/gcms/domain/data/club_member/get_club_member/MemberData.kt
  app/src/main/java/com/msg/gcms/domain/data/club_member/member_expelled/MemberExpelledData.kt
  app/src/main/java/com/msg/gcms/domain/data/user/search_user/GetSearchUserData.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/AfterSchoolListAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/activity_photo/ActivityPhotoType.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/activity_photo/ActivityPhotosAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/add_member/AddMemberAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/add_member/AddMemberType.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/applicant/ApplicantAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/club_list/ClubListAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/club_member/ClubMemberAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/detail_member/DetailMemberAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/detail_photo/DetailPhotoAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/detail_photo/PromotionPicType.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/detail_side_bar/DetailPageSideBar.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/detail_side_bar/DetailSideBarAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/editorial_club/EditorialClubAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/member/MemberAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/user_search/UserSearchAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_introduce/ClubIntroduceFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_type/ClubTypeFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/search_student/StudentSearchFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditSearchFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/MakeClubViewModel.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/MemberManageViewModel.kt
  app/src/main/res/layout/fragment_club_introduce.xml
  app/src/main/res/layout/fragment_club_type.xml
  app/src/main/res/layout/fragment_make_club_detail.xml
  app/src/main/res/layout/fragment_student_search.xml
  app/src/main/res/layout/list_add_member.xml
  app/src/main/res/layout/list_club_picture.xml
  app/src/main/res/layout/list_detail_sidebar.xml
  app/src/main/res/navigation/club_maker_graph.xml
Labels: CORRECTIONS

#263 🔀 :: (#262) - modify call get club list
  app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubDetailViewModel.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/MainViewModel.kt
Labels: FEATURE, CORRECTIONS

#265 🔀 :: (#264) - resolved club detail error
  app/src/main/java/com/msg/gcms/data/remote/network/api/ClubAPI.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubDetailViewModel.kt
Labels: BUG, CORRECTIONS

#251 🔀 :: (#250)회원 탈퇴 로직 수정
  app/src/main/java/com/msg/gcms/data/remote/dto/user/get_my_profile/GetMyProfileResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/network/LoginInterceptor.kt
  app/src/main/java/com/msg/gcms/data/remote/network/api/UserAPI.kt
  app/src/main/java/com/msg/gcms/domain/data/user/get_my_profile/GetMyProfileData.kt
  app/src/main/java/com/msg/gcms/domain/usecase/auth/SaveTokenInfoUseCase.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/withdrawal/WithdrawalActivity.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/AuthViewModel.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/WithdrawalViewModel.kt
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_profile_club.xml
Labels: CORRECTIONS

#269 🔀 :: (#268) - 204 status를 사용하는 부분들을 임시 방편을 넣습니다.
  app/src/main/java/com/msg/gcms/data/mapper/ClubMapper.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/club/get_club_detail/ClubDetailResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/network/api/AuthAPI.kt
  app/src/main/java/com/msg/gcms/data/remote/network/api/ClubAPI.kt
  app/src/main/java/com/msg/gcms/data/remote/network/api/ClubMemberAPI.kt
  app/src/main/java/com/msg/gcms/data/remote/network/api/UserAPI.kt
Labels: CORRECTIONS

#270 🔀 :: (#254)인터셉터 예외처리 방식 변경
  app/src/main/java/com/msg/gcms/data/remote/network/LoginInterceptor.kt
  app/src/main/java/com/msg/gcms/data/remote/util/GCMSApiHandler.kt
  app/src/main/java/com/msg/gcms/domain/exception/NeedLoginException.kt
Labels: CORRECTIONS

#272 🔀 :: 동아리 디테일 페이지 디자인 수정
  app/src/main/res/drawable/bg_detail_club_link.xml
  app/src/main/res/layout/fragment_detail.xml
Labels: CORRECTIONS

#274 🔀 :: api 통신 부분 잘못 지정된 부분 변경
  app/src/main/java/com/msg/gcms/data/remote/dto/user/get_my_profile/ProfileClubResponse.kt
Labels: BUG, CORRECTIONS

#276 Feature/275 setting detail club page from profile page feature
  app/src/main/java/com/msg/gcms/domain/usecase/club/GetDetailUseCase.kt
  app/src/main/java/com/msg/gcms/presentation/view/main/MainActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubDetailViewModel.kt
Labels: FEATURE

#278 🔀 :: (#277)모듈 방식 변경
  app/src/main/java/com/msg/gcms/data/repository/ApplicantRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/data/repository/ClubMemberRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/data/repository/ClubRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/data/repository/ImageRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/di/module/DataSourceModule.kt
  app/src/main/java/com/msg/gcms/di/module/LocalDataSourceModule.kt
  app/src/main/java/com/msg/gcms/di/module/RemoteDataSourceModule.kt
  app/src/main/java/com/msg/gcms/di/module/RepositoryModule.kt
  app/src/main/java/com/msg/gcms/di/module/StorageModule.kt
  app/src/main/java/com/msg/gcms/di/module/UseCaseModule.kt
Labels: FEATURE, CORRECTIONS

#284 🔀 :: (#279) - modify adapter when create club
  app/src/main/java/com/msg/gcms/presentation/adapter/activity_photo/ActivityPhotosAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
Labels: FEATURE, CORRECTIONS

#283 🔀 :: (#281) - modify user search feature
  app/src/main/java/com/msg/gcms/data/remote/dto/club/create_club/CreateClubRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/user/search_user/GetSearchUserResponse.kt
  app/src/main/java/com/msg/gcms/domain/data/club/create_club/CreateClubData.kt
  app/src/main/java/com/msg/gcms/domain/data/user/search_user/GetSearchUserData.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/add_member/AddMemberAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/user_search/UserSearchAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/search_student/StudentSearchFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditSearchFragment.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/MakeClubViewModel.kt
Labels: FEATURE, HELP, CORRECTIONS

#286 🔀 :: (#285) - 디테일 페이지 UI 수정
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_detail.xml
Labels: CORRECTIONS

#289 🔀 :: Changed the API that receives club information when editing club information
  app/src/main/java/com/msg/gcms/presentation/adapter/club_member/ClubMemberAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/user_search/UserSearchAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditSearchFragment.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/EditViewModel.kt
Labels: FEATURE

#295 🔀 :: (#293) 파일 관련 util로 관리
  app/src/main/java/com/msg/gcms/presentation/utils/FileUtil.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileActivity.kt
Labels: FEATURE, REFAC

#296 🔀 :: (#290) - modify club member
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditSearchFragment.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/EditViewModel.kt
Labels: FEATURE

#294 🔀 :: (#282) - 디테일 페이지 갱신 및 예외처리
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/msg/gcms/presentation/base/BaseDialog.kt
  app/src/main/java/com/msg/gcms/presentation/base/BaseModal.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubDetailViewModel.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubViewModel.kt
Labels: CORRECTIONS

#302 🔀 :: (#298) - 디테일 페이지 핫픽스
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubDetailViewModel.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubViewModel.kt
Labels: BUG, CORRECTIONS

#299 🔀 :: (#291) - change the logic that modify activity photo
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
Labels: FEATURE

#303 🔀:: (#300) get club member when club member manage
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/msg/gcms/data/remote/dto/applicant/get_applicant_list/GetApplicantListResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/club_member/get_club_member/GetClubMemberResponse.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/club_member/get_club_member/MemberResponse.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/applicant/ApplicantAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/adapter/member/MemberAdapter.kt
  app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
Labels: FEATURE

#306 🔀 :: 코드 서순 바뀐거 수정
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
Labels: BUG, CORRECTIONS

#308 🔀 :: (#307) - bad req when create club
  app/src/main/java/com/msg/gcms/data/remote/dto/club/modify_club_info/ModifyClubInfoRequest.kt
  app/src/main/java/com/msg/gcms/domain/data/club/modify_club_info/ModifyClubInfoData.kt
  app/src/main/java/com/msg/gcms/presentation/utils/FileUtil.kt
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/EditViewModel.kt
Labels: BUG, CORRECTIONS

#310 ️🔀 :: GCMS 2.0.0으로 업데이트
  app/build.gradle.kts
Labels: DOCS

#309 ️🔀 :: (#280) - change the logic that modify club infomation
  app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
Labels: FEATURE

#311 🔀 :: (#304) - 부장 위임 이슈 해결
  app/src/main/java/com/msg/gcms/data/remote/dto/club_member/delegation_of_manager/DelegationOfManagerRequest.kt
  app/src/main/java/com/msg/gcms/domain/data/club_member/delegation_of_manager/DelegationOfManagerData.kt
  app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/MemberManageViewModel.kt
Labels: FEATURE, CORRECTIONS

#314 🔀 :: (#240) 스켈레톤 화면 적용
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/MainViewModel.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ProfileViewModel.kt
  app/src/main/res/anim/no_anim.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_club.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/shimmer_club.xml
  app/src/main/res/layout/shimmer_detail_info.xml
  app/src/main/res/layout/shimmer_profile.xml
  app/src/main/res/xml/activity_profile_xml_constraintlayout_scene.xml
Labels: FEATURE

#313 🔀 :: (#312) - 동아리 신청자 수락, 거절 관련 모든 이슈 해결
  app/src/main/java/com/msg/gcms/data/remote/dto/applicant/club_apply_accept/ClubApplyAcceptRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/applicant/club_apply_reject/ClubApplyRejectRequest.kt
  app/src/main/java/com/msg/gcms/data/remote/dto/applicant/get_applicant_list/ApplicantListResponse.kt
  app/src/main/java/com/msg/gcms/domain/data/applicant/clubApplyAccept/ClubApplyAcceptData.kt
  app/src/main/java/com/msg/gcms/domain/data/applicant/club_apply_reject/ClubApplyRejectData.kt
  app/src/main/java/com/msg/gcms/domain/data/applicant/get_applicant_list/ApplicantListData.kt
  app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/MemberManageViewModel.kt
Labels: FEATURE, CORRECTIONS

#318 🔀 :: (#317)동아리 생성 이슈 해결
  app/src/main/java/com/msg/gcms/data/remote/network/api/ClubAPI.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/MakeClubViewModel.kt
Labels: BUG, CORRECTIONS

#319 🔀 :: (#315) - in app update
  app/build.gradle.kts
  app/src/main/java/com/msg/gcms/presentation/view/splash/SplashActivity.kt
  app/src/main/java/com/msg/gcms/util/VersionChecker.kt
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
Labels: FEATURE

#327 🔀 :: (#321) - 토큰 변질 검사
  app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileActivity.kt
  app/src/main/java/com/msg/gcms/presentation/view/splash/SplashActivity.kt
Labels: FEATURE, CORRECTIONS

#323 🔀 :: (#320) - the logic of exit club
  app/src/main/java/com/msg/gcms/data/remote/network/api/ClubAPI.kt
  app/src/main/java/com/msg/gcms/data/repository/ClubRepositoryImpl.kt
  app/src/main/java/com/msg/gcms/domain/exception/HttpException.kt
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
  app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubViewModel.kt
Labels: BUG, FEATURE

#329 🔀 :: (#328) - 디테일 페이지 예외처리 수정
  app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
Labels: CORRECTIONS
